# Generated by Django 5.2.1 on 2025-06-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_importer_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='funcname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='lineno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='logger_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='pathname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
