# Generated by Django 5.2.1 on 2025-06-11 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_importer_web', '0002_logentry_funcname_logentry_lineno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='funcname',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='lineno',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='logger_name',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='pathname',
        ),
    ]
