# Generated by Django 5.2.1 on 2025-06-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_importer_web', '0003_remove_logentry_funcname_remove_logentry_lineno_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WindmillReading',
        ),
    ]
