# Generated by Django 5.2.1 on 2025-06-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_importer_web', '0004_delete_windmillreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelDataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locno', models.CharField(blank=True, max_length=50, null=True)),
                ('datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('outdoor_temp', models.CharField(blank=True, max_length=10, null=True)),
                ('wind_speed', models.CharField(blank=True, max_length=10, null=True)),
                ('nacelle_pos', models.CharField(blank=True, max_length=10, null=True)),
                ('active_power', models.CharField(blank=True, max_length=10, null=True)),
                ('frequency', models.CharField(blank=True, max_length=10, null=True)),
                ('source_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('source_email_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Excel Data Entry',
                'verbose_name_plural': 'Excel Data Entries',
                'ordering': ['-datetime', 'locno'],
                'unique_together': {('datetime', 'locno', 'source_filename')},
            },
        ),
    ]
