# Generated by Django 5.2.1 on 2025-06-23 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_importer_web', '0005_exceldataentry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exceldataentry',
            unique_together={('datetime', 'locno')},
        ),
        migrations.RemoveField(
            model_name='exceldataentry',
            name='imported_at',
        ),
        migrations.RemoveField(
            model_name='exceldataentry',
            name='source_email_uid',
        ),
        migrations.RemoveField(
            model_name='exceldataentry',
            name='source_filename',
        ),
    ]
